const nodemailer = require("nodemailer");

const sendEmail = async (to, company, pdfPath) => {
  try {

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to,

      subject: `${company} AI Audit Report`,

      html: `
        <h2>Hello,</h2>

        <p>
          Please find attached your AI-generated business audit report.
        </p>

        <p>
          Generated by SimplifiQ AI Lead System.
        </p>
      `,

      attachments: [
        {
          filename: `${company}-Audit.pdf`,
          path: pdfPath,
        },
      ],
    });

    console.log("Email sent successfully");

  } catch (error) {
    console.error("Email Error:", error.message);
  }
};

module.exports = sendEmail;